# Site settings
title: Cloudy
SEOTitle: 阴天 | 咸鱼前端
header-img: img/post-bg-new.jpg
email: zhykirby@qq.com
description: "心有猛虎，细嗅蔷薇。"
keyword: "Blog, 阴天, zhykirby, andriod, iOS, Apple, iPhone"
url: "http://zhykirby.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhykirby/zhykirby.github.io.git" # you code repository


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "满堂花醉三千客，一剑霜寒十四州。"
sidebar-avatar: /img/avater_m_2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#weibo_username:     阴天Howie
#zhihu_username:     
github_username:    zhykirby
#facebook_username:  
#jianshu_username:   
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 747f13d400dcfca2cc62                            #生成的clientID
  clientSecret: b7415658b607f8ddb0fac35805de950e6394e94b    #生成的clientSecret
  repo: zhykirby.github.io    #仓库名称
  owner: zhykirby    #github用户名
  admin: zhykirby
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: 

# Google Analytics
#ga_track_id:             # Format: UA-xxxxxx-xx
#ga_domain:                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "github",
        href: "http://github.com/zhykirby"
    },{
        title: "一个咸鱼项目Habit",
        href: "http://www.zhykirby.com"
    },{
        title: "炎忍的blog：心之所愿，无所不成。",
        href: "http://blog.endureblaze.cn"
    }
]
